import type {
  User,
  Product,
  Order,
  Category,
  DashboardStats,
  RevenueData,
  TopProduct,
  StockMovement,
} from "./types"

// Mock Categories
export const categories: Category[] = [
  { id: "cat-1", name: "Ciment", slug: "ciment", description: "Ciments et mortiers", icon: "Box", createdAt: new Date(), updatedAt: new Date() },
  { id: "cat-2", name: "Acier et armature", slug: "acier", description: "Barres d'armature et acier", icon: "Layers", createdAt: new Date(), updatedAt: new Date() },
  { id: "cat-3", name: "Bois", slug: "bois", description: "Bois de construction", icon: "TreePine", createdAt: new Date(), updatedAt: new Date() },
  { id: "cat-4", name: "Plomberie", slug: "plomberie", description: "Tuyaux et accessoires", icon: "Droplets", createdAt: new Date(), updatedAt: new Date() },
  { id: "cat-5", name: "Electricité", slug: "electricite", description: "Câbles et équipements", icon: "Zap", createdAt: new Date(), updatedAt: new Date() },
  { id: "cat-6", name: "Outils", slug: "outils", description: "Outils de construction", icon: "Wrench", createdAt: new Date(), updatedAt: new Date() },
]

// Mock Products
export const products: Product[] = [
  {
    id: "prod-1",
    name: "Ciment Portland CEM I 42.5",
    slug: "ciment-portland-cem-i",
    description: "Ciment haute résistance pour construction",
    price: 85.00,
    unit: "sac 50kg",
    sku: "CIM-001",
    barcode: "1234567890123",
    stock: 450,
    minStock: 100,
    maxStock: 1000,
    categoryId: "cat-1",
    category: categories[0],
    imageUrl: null,
    images: [],
    isFeatured: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-2",
    name: "Barre d'armature HA 12mm",
    slug: "barre-armature-ha-12",
    description: "Barre à haute adhérence 12mm x 12m",
    price: 125.00,
    unit: "barre",
    sku: "ARM-012",
    barcode: "1234567890124",
    stock: 280,
    minStock: 50,
    maxStock: 500,
    categoryId: "cat-2",
    category: categories[1],
    imageUrl: null,
    images: [],
    isFeatured: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-3",
    name: "Chevron Sapin 60x80mm",
    slug: "chevron-sapin-60x80",
    description: "Chevron en bois de sapin traité",
    price: 45.00,
    unit: "mètre",
    sku: "BOS-060",
    barcode: "1234567890125",
    stock: 12,
    minStock: 50,
    maxStock: 200,
    categoryId: "cat-3",
    category: categories[2],
    imageUrl: null,
    images: [],
    isFeatured: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-4",
    name: "Tuyau PVC 100mm",
    slug: "tuyau-pvc-100",
    description: "Tuyau PVC pour évacuation",
    price: 32.50,
    unit: "mètre",
    sku: "PLB-100",
    barcode: "1234567890126",
    stock: 8,
    minStock: 30,
    maxStock: 150,
    categoryId: "cat-4",
    category: categories[3],
    imageUrl: null,
    images: [],
    isFeatured: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-5",
    name: "Câble électrique 2.5mm²",
    slug: "cable-electrique-2-5",
    description: "Câble électrique cuivre isolé",
    price: 2.80,
    unit: "mètre",
    sku: "ELC-025",
    barcode: "1234567890127",
    stock: 1500,
    minStock: 500,
    maxStock: 5000,
    categoryId: "cat-5",
    category: categories[4],
    imageUrl: null,
    images: [],
    isFeatured: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-6",
    name: "Perceuse à percussion 750W",
    slug: "perceuse-percussion-750w",
    description: "Perceuse professionnelle",
    price: 890.00,
    unit: "unité",
    sku: "OUT-750",
    barcode: "1234567890128",
    stock: 25,
    minStock: 10,
    maxStock: 50,
    categoryId: "cat-6",
    category: categories[5],
    imageUrl: null,
    images: [],
    isFeatured: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-7",
    name: "Mortier colle carrelage",
    slug: "mortier-colle-carrelage",
    description: "Mortier colle pour carrelage intérieur/extérieur",
    price: 65.00,
    unit: "sac 25kg",
    sku: "CIM-002",
    barcode: "1234567890129",
    stock: 180,
    minStock: 50,
    maxStock: 300,
    categoryId: "cat-1",
    category: categories[0],
    imageUrl: null,
    images: [],
    isFeatured: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-8",
    name: "Treillis soudé ST25",
    slug: "treillis-soude-st25",
    description: "Treillis soudé pour dalle béton",
    price: 78.00,
    unit: "panneau",
    sku: "ARM-ST25",
    barcode: "1234567890130",
    stock: 45,
    minStock: 20,
    maxStock: 100,
    categoryId: "cat-2",
    category: categories[1],
    imageUrl: null,
    images: [],
    isFeatured: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock Users
export const users: User[] = [
  {
    id: "user-1",
    email: "ahmed.abouhijazi@example.com",
    name: "Ahmed Abouhijazi",
    phone: "+212 6 12 34 56 78",
    role: "ADMIN",
    avatar: null,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: "user-2",
    email: "fatima.benali@example.com",
    name: "Fatima Benali",
    phone: "+212 6 23 45 67 89",
    role: "MANAGER",
    avatar: null,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date(),
    lastLoginAt: new Date("2025-01-20"),
    isActive: true,
  },
  {
    id: "user-3",
    email: "mohammed.tazi@example.com",
    name: "Mohammed Tazi",
    phone: "+212 6 34 56 78 90",
    role: "STAFF",
    avatar: null,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date(),
    lastLoginAt: new Date("2025-01-22"),
    isActive: true,
  },
  {
    id: "user-4",
    email: "sara.alaoui@example.com",
    name: "Sara Alaoui",
    phone: "+212 6 45 67 89 01",
    role: "CUSTOMER",
    avatar: null,
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date(),
    lastLoginAt: new Date("2025-01-18"),
    isActive: true,
  },
  {
    id: "user-5",
    email: "youssef.idrissi@example.com",
    name: "Youssef Idrissi",
    phone: "+212 6 56 78 90 12",
    role: "CUSTOMER",
    avatar: null,
    createdAt: new Date("2024-06-20"),
    updatedAt: new Date(),
    lastLoginAt: new Date("2025-01-15"),
    isActive: true,
  },
  {
    id: "user-6",
    email: "amina.fassi@example.com",
    name: "Amina Fassi",
    phone: "+212 6 67 89 01 23",
    role: "CUSTOMER",
    avatar: null,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date(),
    lastLoginAt: null,
    isActive: false,
  },
]

// Mock Orders
export const orders: Order[] = [
  {
    id: "ord-1",
    orderNumber: "CMD-2025-001",
    userId: "user-4",
    user: users[3],
    status: "DELIVERED",
    paymentStatus: "PAID",
    subtotal: 1250.00,
    tax: 250.00,
    shipping: 50.00,
    total: 1550.00,
    shippingAddress: "123 Rue Mohammed V, Casablanca",
    billingAddress: "123 Rue Mohammed V, Casablanca",
    notes: null,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-18"),
    items: [
      { id: "item-1", orderId: "ord-1", productId: "prod-1", product: products[0], quantity: 10, unitPrice: 85.00, total: 850.00 },
      { id: "item-2", orderId: "ord-1", productId: "prod-2", product: products[1], quantity: 3, unitPrice: 125.00, total: 375.00 },
    ],
  },
  {
    id: "ord-2",
    orderNumber: "CMD-2025-002",
    userId: "user-5",
    user: users[4],
    status: "PROCESSING",
    paymentStatus: "PAID",
    subtotal: 890.00,
    tax: 178.00,
    shipping: 0.00,
    total: 1068.00,
    shippingAddress: "45 Avenue Hassan II, Rabat",
    billingAddress: "45 Avenue Hassan II, Rabat",
    notes: "Livraison le matin de préférence",
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
    items: [
      { id: "item-3", orderId: "ord-2", productId: "prod-6", product: products[5], quantity: 1, unitPrice: 890.00, total: 890.00 },
    ],
  },
  {
    id: "ord-3",
    orderNumber: "CMD-2025-003",
    userId: "user-4",
    user: users[3],
    status: "PENDING",
    paymentStatus: "PENDING",
    subtotal: 325.00,
    tax: 65.00,
    shipping: 30.00,
    total: 420.00,
    shippingAddress: "123 Rue Mohammed V, Casablanca",
    billingAddress: "123 Rue Mohammed V, Casablanca",
    notes: null,
    createdAt: new Date("2025-01-22"),
    updatedAt: new Date("2025-01-22"),
    items: [
      { id: "item-4", orderId: "ord-3", productId: "prod-4", product: products[3], quantity: 10, unitPrice: 32.50, total: 325.00 },
    ],
  },
  {
    id: "ord-4",
    orderNumber: "CMD-2025-004",
    userId: "user-5",
    user: users[4],
    status: "SHIPPED",
    paymentStatus: "PAID",
    subtotal: 2340.00,
    tax: 468.00,
    shipping: 100.00,
    total: 2908.00,
    shippingAddress: "45 Avenue Hassan II, Rabat",
    billingAddress: "45 Avenue Hassan II, Rabat",
    notes: null,
    createdAt: new Date("2025-01-19"),
    updatedAt: new Date("2025-01-21"),
    items: [
      { id: "item-5", orderId: "ord-4", productId: "prod-1", product: products[0], quantity: 20, unitPrice: 85.00, total: 1700.00 },
      { id: "item-6", orderId: "ord-4", productId: "prod-7", product: products[6], quantity: 8, unitPrice: 65.00, total: 520.00 },
    ],
  },
  {
    id: "ord-5",
    orderNumber: "CMD-2025-005",
    userId: "user-4",
    user: users[3],
    status: "CANCELLED",
    paymentStatus: "REFUNDED",
    subtotal: 450.00,
    tax: 90.00,
    shipping: 25.00,
    total: 565.00,
    shippingAddress: "123 Rue Mohammed V, Casablanca",
    billingAddress: "123 Rue Mohammed V, Casablanca",
    notes: "Client a annulé",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-11"),
    items: [
      { id: "item-7", orderId: "ord-5", productId: "prod-3", product: products[2], quantity: 10, unitPrice: 45.00, total: 450.00 },
    ],
  },
]

// Mock Stock Movements
export const stockMovements: StockMovement[] = [
  { id: "mov-1", productId: "prod-1", product: products[0], type: "IN", quantity: 200, reason: "Réception fournisseur", reference: "BON-001", createdAt: new Date("2025-01-15"), createdBy: "user-2" },
  { id: "mov-2", productId: "prod-1", product: products[0], type: "OUT", quantity: 30, reason: "Vente CMD-2025-001", reference: "CMD-2025-001", createdAt: new Date("2025-01-15"), createdBy: null },
  { id: "mov-3", productId: "prod-2", product: products[1], type: "IN", quantity: 100, reason: "Réception fournisseur", reference: "BON-002", createdAt: new Date("2025-01-18"), createdBy: "user-2" },
  { id: "mov-4", productId: "prod-3", product: products[2], type: "ADJUSTMENT", quantity: -5, reason: "Correction inventaire", reference: null, createdAt: new Date("2025-01-20"), createdBy: "user-3" },
  { id: "mov-5", productId: "prod-4", product: products[3], type: "OUT", quantity: 10, reason: "Vente CMD-2025-003", reference: "CMD-2025-003", createdAt: new Date("2025-01-22"), createdBy: null },
]

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalRevenue: 156420.00,
  revenueChange: 12.5,
  totalOrders: 248,
  ordersChange: 8.2,
  totalProducts: products.length,
  lowStockProducts: products.filter(p => p.stock < p.minStock).length,
  totalUsers: users.filter(u => u.role === "CUSTOMER").length,
  usersChange: 15.3,
}

// Revenue Data for Charts
export const revenueData: RevenueData[] = [
  { month: "Août", revenue: 98500, orders: 145 },
  { month: "Sept", revenue: 112300, orders: 168 },
  { month: "Oct", revenue: 125800, orders: 192 },
  { month: "Nov", revenue: 138200, orders: 215 },
  { month: "Déc", revenue: 145600, orders: 232 },
  { month: "Jan", revenue: 156420, orders: 248 },
]

// Top Products
export const topProducts: TopProduct[] = [
  { id: "prod-1", name: "Ciment Portland CEM I 42.5", sales: 1250, revenue: 106250 },
  { id: "prod-2", name: "Barre d'armature HA 12mm", sales: 890, revenue: 111250 },
  { id: "prod-5", name: "Câble électrique 2.5mm²", sales: 4500, revenue: 12600 },
  { id: "prod-6", name: "Perceuse à percussion 750W", sales: 42, revenue: 37380 },
  { id: "prod-7", name: "Mortier colle carrelage", sales: 320, revenue: 20800 },
]
